# Generated by Django 2.2.4 on 2019-09-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='Faculty',
            new_name='faculty',
        ),
    ]
